# Generated by Django 2.1 on 2019-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='best_spree',
            field=models.IntegerField(default=0),
        ),
    ]
