# Generated by Django 2.1 on 2019-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerStats', '0003_auto_20190227_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='best_spree_game_map',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='best_spree_game_type',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='best_spree_game_variant',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_game_map',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_game_type',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_game_variant',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
