# Generated by Django 2.1 on 2019-02-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerStats', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
