# Generated by Django 2.1 on 2019-04-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerStats', '0006_auto_20190227_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='isMember',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(to='playerStats.Player'),
        ),
    ]
