# Generated by Django 2.2.1 on 2019-06-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerStats', '0008_motd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motd',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
