# Generated by Django 2.2.1 on 2019-06-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerStats', '0009_auto_20190605_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
